### ISSUE TITLE
Auto Claim Drops Fails for Nitro Stream Racing (Firefox)

### ISSUE THREAD

**Issue by shangles** [schulzjona/twitch_inventory_claimer_issues#1]
## Description
Firefox extension seems to be working for some streams but not others.  Today I'm watching a stream to get drops for Nitro: Stream Racing (this stream in particular:  https://www.twitch.tv/ovidiuz94) and for the first of four drops I'm presented with the manual Claim button to claim my drop.  I'm going to continue to watch the stream and see if anything changes, but wanted to report this here (instead of through the Firefox review page for the extension)

## To Reproduce
Watch the Nitro: Stream Racing stream (https://www.twitch.tv/ovidiuz94) for one hour to see if it auto-claims the drop.  Use Firefox for Windows version 120.0 (64-bit) and extension version 2.1.1.

## Expected Behavior
Drop should auto-claim

## Screenshots
N/A

## Environment
[//]: # (Please complete the following information:)
- OS: Windows 10 Pro 22H2 19045.3693
- Browser Firefox 120.0 (64-bit)
- Version 2.1.1

## Additional Context
N/A

**Comment by schulzjona** [comment]
Gonna look into this asap! Sometimes it takes a few minutes to claim the drop, it is usual for twitch to still show the claim thingy in the chat. Gonna try to prevent that in a future patch

**Comment by shangles** [comment]
Thanks!  I'll keep you posted here.  I'm 73% to my next hourly drop.  If it doesn't auto-claim immediately, I'll wait patiently for 10-15 minutes and report back here with results.

To confirm, I don't have to have the stream actively open in Firefox, right?  I can have any tab/window be active for this to work in the background?

**Comment by schulzjona** [comment]
Correct, as long as the stream is running in the background it is fine. However i dont think you are allowed to mute the stream itself, you have to mute it via the Rightclick menu on the tab.

**Comment by shangles** [comment]
> Correct, as long as the stream is running in the background it is fine. However i dont think you are allowed to mute the stream itself, you have to mute it via the Rightclick menu on the tab.

Cool, yeah that was my understanding as well.  I've been keeping volume on for the stream but muting the tab.

**Comment by shangles** [comment]
Update.  I refreshed the Drops page after waiting about 7 minutes and it seemed to have worked (auto-claim)

**Comment by schulzjona** [comment]
Looks good to me. So i guess the next step for me would be to remove or change the claim thing in the chat window, right?

**Comment by shangles** [comment]
I'll let you make that call.  I'm just happy this is working as intended now :)

**Comment by schulzjona** [comment]
Ok, gonna start on that next weekend :) Glad its working for you now.

**Comment by shangles** [comment]
Requesting to open this ticket again as I'm actively trying to get Sea of Thieves drops today and the first drop (of 4 total) auto claimed without issue, but so far the second and third have not.  Even though I waited ~10 minutes after I got the notification that a drop was available.
