### ISSUE TITLE
Auto Claim Drops Fails for Sea of Thieves (Firefox)

### ISSUE THREAD

**Issue by shangles** [schulzjona/twitch_inventory_claimer_issues#2]
Related to this Issue https://github.com/schulzjona/twitch_inventory_claimer_issues/issues/1

Currently closed and I can't seem to re-open it.

I'm actively trying to get Sea of Thieves drops today and the first drop (of 4 total) auto claimed without issue, but so far the second and third have not. Even though I waited ~10 minutes after I got the notification that a drop was available.

**Comment by schulzjona** [comment]
Hi, currently working on another update, might take another week or so, as of the intense testing needed :)

**Comment by shangles** [comment]
No worries.  Take your time.  Thanks for all your hard work!

**Comment by shangles** [comment]
Oddly, I've been watching a Stream Raiders stream today and so far it's automatically claimed 4 of 5 drops without me needing to do anything.  I'm 60% towards the final drop. 

UPDATE:  All 5 drops claimed without issue for this game and stream (https://www.twitch.tv/meistar_)

**Comment by schulzjona** [comment]
Would be interesting to know if the addon displays the drop as claimed. Could you look it up when it happens next? 
![grafik](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/20225781/3efd9cf2-f280-4f7b-83fd-6c13bd496bfe)
![grafik](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/20225781/fe5fda53-88f7-4aa3-b4db-2ffafe505fef)

you can check it by opening the addon menu and then clicking on the campaign. if there is a green checkmark, it is actually claimed and confirmed by the twitch api. If not, please report here again :)

**Comment by shangles** [comment]
I'm testing now with a World of Warships stream (https://www.twitch.tv/boccaboi)
I honestly have never seen that add-on options page before, lol.

![PrtScr capture](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/9053908/d6773f6a-6388-4eb6-9e24-a9c19abe4d1c)

![PrtScr capture_2](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/9053908/c670cd45-fd3d-4128-96cb-460d4d3af4d3)


I just sent you a little $$ via your support me page :)

**Comment by shangles** [comment]
When I get time, and finish paying my bills, I'll send you some more.  I love supporting active devs with great support and communication :)

**Comment by shangles** [comment]
So far so good.  First drop auto-claimed without manual intervention.
![PrtScr capture](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/9053908/5cadb9cc-9d86-4150-850c-3651c898b08b)

UPDATE:  Both drops for this campaign successfully claimed automatically.

**Comment by schulzjona** [comment]
Perfect, and did twitch show any "falsy" claim buttons?

**Comment by shangles** [comment]
Not when I refreshed my drop progress page this time.

**Comment by shangles** [comment]
There's another Sea of Thieves drop campaign live now.  I'm watching a stream and will report any interesting info.

**Comment by shangles** [comment]
No issues encountered this time.  All six drops automatically claimed without a problem.
