### ISSUE TITLE
Hovering Over 5 latest claims, the image is cut off

### ISSUE THREAD

**Issue by shangles** [schulzjona/twitch_inventory_claimer_issues#4]
# Bug Report

## Description
When you hover over the 5 images in "5 latest claims" screen, the pop-up image is cut off.

## To Reproduce
Hover over one of the latest claims

## Expected Behavior
You should be able to see the entire pop-up image

## Screenshots
![PrtScr capture](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/9053908/461eba5d-1a68-4c26-8520-27ee14592054)

## Environment
[//]: # (Please complete the following information:)
- OS: Windows 10 Pro
- Browser Firefox 123.0.1 64-bit
- Version 3.1.1

## Additional Context
N/A

**Comment by schulzjona** [comment]
Update should roll out soon, pinging you when it is done 👌

**Comment by Tallefer** [comment]
also sometimes when opened after some time of inactivity the window looks like this or similarly cropped (but usually fixes itself after several retries)
![image](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/395476/83146cbf-b43a-4d5d-8726-2dbc8abfc397)

**Comment by shangles** [comment]
I guess I'm also looking for clarification on what the "Channelpoints claimed" section of the extension window is.  It looks like it's a leaderboard of sorts?  If so, can that be made an option to hide that section alltogether?  I really only care about seeing my active points/rewards that I'm currently working towards, and no historical data / gamification stats.

**Comment by schulzjona** [comment]
Working on it, maybe by end of week there will be fixes for both issues. Keeping u both updated here

@shangles gonna make things more customizable, so users can select what panels are shown in the ui :)

**Comment by shangles** [comment]
I am now realizing that the Channelpoints claimed section is just keeping track of personal progress.  I guess I must only have 5 channels currently tracked, because if I click Show All I still only see 5.

Thanks for your work on this extension.  It's solid.  Best one I've tried over the past few years.

**Comment by schulzjona** [comment]
![image](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/20225781/1068fdee-88e6-40ab-ae7b-c3d329b8d8fc)

just added those options. expecting to ship the update sometime next week

**Comment by schulzjona** [comment]
New update is now rolling out, lmk if there are any more issues :)

**Comment by Tallefer** [comment]
...spoke too soon :D
currently there are 2-3 drops in progress, but the popup briefly shows up (mostly empty though), then shrinks to this. restarting the addon didn't help
![image](https://github.com/schulzjona/twitch_inventory_claimer_issues/assets/395476/2cbc672e-b633-4bb6-9aab-3ad13fc67978)

**Comment by schulzjona** [comment]
@Tallefer  found the culprit, an query key that expired... trying to upload the fix this evening
