### ISSUE TITLE
TopSpin 2K25 Drops Not Auto-Claiming

### ISSUE THREAD

**Issue by shangles** [schulzjona/twitch_inventory_claimer_issues#5]
# Bug Report

## Description
I'm not sure if something changed recently with the Twitch drops, but today I've been watching streams for TopSpin 2K25 and I've watched enough to get 2 of the 3 drops, but I still see the "Claim Now" button when refreshing my Inventory page.

This plug-in has been rock-solid since I started using it so I suspect this is a Twitch or TopSpin issue.

## To Reproduce
Watch multiple hours of a TopSpin 2K25 (tennis) game with Drops enabled.

## Expected Behavior
The plug-in should auto claim the drops after a minute or so.

## Screenshots
![PrtScr capture](https://github.com/user-attachments/assets/13dbc023-1c7f-445f-8db4-c61e62116b86)

## Environment
[//]: # (Please complete the following information:)
- OS: Windows 10 Professional 64-bit
- Browser:  Firefox
- Version:  129.0.1 (64-bit)

## Additional Context
Twitch Inventory Claimer version:  3.3.0

**Comment by shangles** [comment]
I'm going to stop watching a TopSpin 2K25 stream and watch a Stream Raiders stream to see if those drops auto-claim.

**Comment by shangles** [comment]
It looks like the first drop for Stream Raiders did eventually auto-claim.   Going back to the last drop now for TopSpin

**Comment by shangles** [comment]
Not sure what happened but the last drop for TopSpin 2K25 claimed automatically.  Closing this out for now.

**Comment by schulzjona** [comment]
Thank you for the Report. I will try to reproduce it the issue when i have some spare time, that behaviour should Not Happen 😄
